# TBC爬虫YAML配置文件
CrawlerInfo:
  RecrawlCount: 10
  CrawlerOffset: 824200
  CrawlerCount: 16

CoinType: "TBC"

Fullnode:
  URL: 
    - "vsa23rewfdsfaddasd1:rgfdv213edas@127.0.0.1:8332"
  ZMQURL:
    - "tcp://127.0.0.1:28333"
  NETTYPE: "mainnet"

# 健康检查配置
HealthCheck:
  ReportURL: "http://127.0.0.1:8081/tbc/health/heartbeat"
  ReportInterval: 15


RedisDbPaths:
  vout: "redis://127.0.0.1:6379/13"

Type: "vout_filter"

LogConfig:
  LogDir: "./logs/mainnet/vout.log"
  LogLevel: "INFO"

